import Navbar from "./shared/navbar"
import WordGenerator from "./shared/wordgenerator"
import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body  >
        <div  className="text-3xl font-bold underline text-red-300 bg-red-900">

       <Navbar/>
        </div>
        {children}
        <WordGenerator/>
        </body>
    </html>
  )
}
